### ISSUE TITLE
app.use() requires a middleware function

### ISSUE THREAD

**Issue by samjaninf** [mercerbe/SocialRent#3]
Hey, I really like what you guys are doing here, Wanted to spin it up and give it a look-see but I ran into this issue:

````
/opt/node_modules/express/lib/application.js:210
    throw new TypeError('app.use() requires a middleware function')
    ^

TypeError: app.use() requires a middleware function
    at Function.use (/opt/node_modules/express/lib/application.js:210:11)
    at Object.<anonymous> (/opt/server.js:20:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
````
````
➜  git:(master) ✗ node --version
v10.8.0
➜  git:(master) ✗ npm -v
6.2.0
➜  git:(master) ✗ mongo --version
MongoDB shell version v4.0.1
git version: 54f1582fc6eb01de4d4c42f26fc133e623f065fb
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
allocator: tcmalloc
modules: none
build environment:
    distmod: rhel70
    distarch: x86_64
    target_arch: x86_64

➜  git:(master) ✗ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

````

Good luck.

**Comment by mercerbe** [comment]
Hey! Appreciate the interest in our project. We're actually still in development right now, planning on having everything functional and launched in about 2 weeks. We'll be merging to the master over the next week and it should be ready to clone and use then.
